version: '3'
services:
        web:
                image: ramen_kj_v1
                build: .
                ports:
                        - "8099:8080"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped
